-- Generated by Oracle SQL Developer Data Modeler 20.2.0.167.1538
--   at:        2020-11-06 15:32:07 GMT
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c



DROP TABLE artist CASCADE CONSTRAINTS;

DROP TABLE artstyle CASCADE CONSTRAINTS;

DROP TABLE arttype CASCADE CONSTRAINTS;

DROP TABLE artwork CASCADE CONSTRAINTS;

DROP TABLE custlikeart CASCADE CONSTRAINTS;

DROP TABLE custlikeartists CASCADE CONSTRAINTS;

DROP TABLE customer CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE artist (
    artistid   NUMBER(7) NOT NULL,
    aname      VARCHAR2(30) NOT NULL,
    artistage  NUMBER(3) NOT NULL,
    artstyle   VARCHAR2(30)
)
LOGGING;

ALTER TABLE artist ADD CONSTRAINT artist_pk PRIMARY KEY ( artistid );

CREATE TABLE artstyle (
    styleid          NUMBER(7) NOT NULL,
    styledesc        VARCHAR2(30),
    artist_artistid  NUMBER(7)
)
LOGGING;

taddress  VARCHAR2(30) NOT NULL,
    amountspent  NUMBER(9, 2) NOT NULL
)
LOGGING;

ALTER TABLE customer ADD CONSTRAINT customer_pk PRIMARY KEY ( custid );

ALTER TABLE artstyle
    ADD CONSTRAINT artstyle_artist_fk FOREIGN KEY ( artist_artistid )
        REFERENCES artist ( artistid )
    NOT DEFERRABLE;

ALTER TABLE arttype
    ADD CONSTRAINT arttype_artwork_fk FOREIGN KEY ( artwork_artworkid )
        REFERENCES artwork ( artworkid )
    NOT DEFERRABLE;

ALTER TABLE custlikeart
    ADD CONSTRAINT custlikeart_artstyle_fk FOREIGN KEY ( artstyle_styleid )
        REFERENCES artstyle ( styleid )
    NOT DEFERRABLE;

ALTER TABLE custlikeart
    ADD CONSTRAINT custlikeart_customer_fk FOREIGN KEY ( customer_custid )
        REFERENCES customer ( custid )
    NOT DEFERRABLE;

ALTER TABLE custlikeartists
    ADD CONSTRAINT custlikeartists_artist_fk FOREIGN KEY ( artist_artistid )
        REFERENCES artist ( artistid )
    NOT DEFERRABLE;

ALTER TABLE custlikeartists
    ADD CONSTRAINT custlikeartists_customer_fk FOREIGN KEY ( customer_custid )
        REFERENCES customer ( custid )
    NOT DEFERRABLE;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             0
-- ALTER TABLE                             13
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
